version: "3.2"
services:
  audio_test:
    build: .
    image: audio_test
    container_name: audio_test
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    command: go run main.go